name: Main
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Freeze HTML
      run: |
        python bookshelf.py freeze -v
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Deploy
      run: |
        python bookshelf.py deploy --no-freeze --push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
